#include "simplewavwriter.h"
#include <QDateTime>
#include <QDebug>
#include <QAudioFormat>
#include <QAudioOutput>
#include <QBuffer>
#include <cmath>
#include <cstdlib>
#include <ctime>
#include <algorithm>

SimpleWavWriter::SimpleWavWriter(QObject *parent)
    : QObject(parent)
    , m_isRecording(false)
    , m_isPaused(false)
    , m_startTime(0)
    , m_pauseTime(0)
    , m_sampleRate(16000)
    , m_bassVolumeMultiplier(2.0)
    , m_playbackSpeed(1.0)
    , m_masterVolume(1.0)
{
    std::srand(std::time(nullptr));
    
    // Инициализируем дорожки (теперь 7 дорожек)
    m_tracks.resize(MAX_TRACKS);
    for (int i = 0; i < MAX_TRACKS; i++) {
        m_tracks[i].name = QString("Track %1").arg(i + 1);
        m_tracks[i].instrument = 0;
        m_tracks[i].volume = 1.0;
        m_tracks[i].muted = false;
    }
}

SimpleWavWriter::~SimpleWavWriter()
{
}

bool SimpleWavWriter::startRecording(int sampleRate)
{
    if (m_isRecording) {
        stopRecording();
    }
    
    // Очищаем все дорожки
    clearAllTracks();
    
    m_isRecording = true;
    m_isPaused = false;
    m_startTime = QDateTime::currentMSecsSinceEpoch() / 1000.0;
    m_pauseTime = 0;
    m_sampleRate = sampleRate;
    
    qDebug() << "Started recording, sample rate:" << m_sampleRate;
    return true;
}

bool SimpleWavWriter::pauseRecording()
{
    if (!m_isRecording || m_isPaused) {
        return false;
    }
    
    m_isPaused = true;
    m_pauseTime = QDateTime::currentMSecsSinceEpoch() / 1000.0;
    qDebug() << "Recording paused";
    return true;
}

bool SimpleWavWriter::resumeRecording()
{
    if (!m_isRecording || !m_isPaused) {
        return false;
    }
    
    // Корректируем время начала для новых событий
    double pauseDuration = (QDateTime::currentMSecsSinceEpoch() / 1000.0) - m_pauseTime;
    m_startTime += pauseDuration;
    
    m_isPaused = false;
    qDebug() << "Recording resumed, pause duration:" << pauseDuration;
    return true;
}

bool SimpleWavWriter::stopRecording()
{
    if (!m_isRecording) {
        return false;
    }
    
    m_isRecording = false;
    m_isPaused = false;
    
    // Генерируем аудиоданные для быстрого воспроизведения
    generateAllTracksAudio();
    
    qDebug() << "Stopped recording";
    qDebug() << "Track information:";
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (!m_tracks[i].events.isEmpty()) {
            qDebug() << "  Track" << i << ":" << m_tracks[i].name 
                     << ", events:" << m_tracks[i].events.size()
                     << ", duration:" << getTrackDuration(i) << "seconds";
        }
    }
    
    return true;
}

bool SimpleWavWriter::saveToFile(const QString &filename)
{
    QByteArray audioData = getMergedAudioData();
    if (audioData.isEmpty()) {
        qDebug() << "No audio data to save";
        return false;
    }
    
    QFile file(filename);
    if (!file.open(QIODevice::WriteOnly)) {
        qDebug() << "Cannot open file for writing:" << filename;
        return false;
    }
    
    QDataStream stream(&file);
    stream.setByteOrder(QDataStream::LittleEndian);
    
    writeWavHeader(stream, audioData.size());
    stream.writeRawData(audioData.constData(), audioData.size());
    
    file.close();
    qDebug() << "WAV file saved:" << filename << "size:" << audioData.size() << "bytes";
    return true;
}

bool SimpleWavWriter::saveToMusicFile(const QString &filename)
{
    QFile file(filename);
    if (!file.open(QIODevice::WriteOnly | QIODevice::Text)) {
        qDebug() << "Cannot open music file for writing:" << filename;
        return false;
    }
    
    QTextStream stream(&file);
    stream.setCodec("UTF-8");
    
    // File header
    stream << "; Music composition generated by Yamitracker\n";
    stream << "; Format: Pently-style with tracks\n";
    stream << "; Creation time: " << QDateTime::currentDateTime().toString("yyyy-MM-dd hh:mm:ss") << "\n";
    stream << "; Number of tracks: ";
    
    int activeTracks = 0;
    for (int i = 0; i < MAX_TRACKS; i++) {
        if (!m_tracks[i].events.isEmpty()) {
            activeTracks++;
        }
    }
    stream << activeTracks << "\n\n";
    
    stream << ".include \"pentlyseq.inc\"\n";
    stream << ".segment \"SPCIMAGE\"\n\n";
    
    // Instrument table (using standard Pently instruments)
    stream << "; Instrument table\n";
    stream << "music_inst_table:\n";
    stream << "  ;    name         lv  rv frq smp att dec sus lvl\n";
    stream << "  INST KICK,        11, 10,  3,  6, 31, 17,  0,  8\n";
    stream << "  INST SNARE,       10, 15,  3,  7, 31, 17,  0,  8\n";
    stream << "  INST HAT,          3,  5,  3,  5, 31, 17,  0,  8\n";
    stream << "  INST PLING_8,      3, 10,  1,  0, 31, 19, 15,  2\n";
    stream << "  INST PLING_4,      7,  7,  1,  1, 31, 19, 15,  2\n";
    stream << "  INST PLING_2,      9,  6,  1,  2, 31, 17, 15,  2\n";
    stream << "  INST BASSGUITAR,  12, 12,  1,  4, 31, 17, 15,  8\n";
    stream << "  INST BASSCLAR,    12, 12,  1,  2, 21, 21, 27,  4\n";
    stream << "  INST HORNBLAT,     3,  9,  1,  0, 21, 21, 27,  4\n";
    stream << "  INST XYLSHORT,    10,  6,  1,  2, 31, 23, 20,  2\n";
    stream << "  INST XYLMED,      10,  6,  1,  2, 31, 19, 17,  2\n\n";
    
    // Generate patterns for each track
    stream << "pently_patterns:\n";
    
    QMap<int, QVector<QVector<WavEvent>>> trackPatterns;
    int totalPatternCount = 0;
    
    // First collect all patterns from all tracks
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (m_tracks[track].events.isEmpty()) continue;
        
        // Group events by time to create patterns (1 second groups)
        QVector<QVector<WavEvent>> patternGroups = groupEventsByTime(track, 1.0);
        trackPatterns[track] = patternGroups;
        totalPatternCount += patternGroups.size();
    }
    
    // Now write all patterns with proper indexing
    int currentPatternIndex = 0;
    QMap<int, QMap<int, int>> trackPatternIndices; // track -> group index -> pattern index
    
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (!trackPatterns.contains(track)) continue;
        
        const QVector<QVector<WavEvent>>& patterns = trackPatterns[track];
        
        for (int groupIdx = 0; groupIdx < patterns.size(); groupIdx++) {
            const QVector<WavEvent>& patternEvents = patterns[groupIdx];
            
            stream << QString("PPDAT_track%1_pattern%2:\n").arg(track).arg(groupIdx);
            
            // Determine instrument for this track
            QString instrumentName = getInstrumentMacroName(m_tracks[track].instrument);
            
            // Check if pattern has different instruments
            bool hasDifferentInstruments = false;
            int firstInstrument = patternEvents.isEmpty() ? 0 : patternEvents[0].instrument;
            for (const auto& event : patternEvents) {
                if (event.instrument != firstInstrument && !event.isPause) {
                    hasDifferentInstruments = true;
                    break;
                }
            }
            
            // Always add instrument command at start of pattern
            stream << QString("  .byt INSTRUMENT, %1\n").arg(instrumentName);
            
            // Add notes
            for (const auto& event : patternEvents) {
                QString noteCmd = getNoteCommand(event, false);
                if (!noteCmd.isEmpty()) {
                    stream << "  .byt " << noteCmd << "\n";
                }
            }
            
            stream << "  .byt PATEND\n";
            
            // Store the pattern index for this track and group
            if (!trackPatternIndices.contains(track)) {
                trackPatternIndices[track] = QMap<int, int>();
            }
            trackPatternIndices[track][groupIdx] = currentPatternIndex;
            currentPatternIndex++;
        }
    }
    
    // Generate song data
    stream << "\npently_songs:\n";
    stream << ".addr  PSDAT_composition\n\n";
    
    stream << "; Main composition\n";
    stream << "PSDAT_composition:\n";
    stream << "  setTempo 300\n\n";
    
    // Calculate maximum number of pattern groups across all tracks
    int maxGroups = 0;
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (trackPatterns.contains(track)) {
            maxGroups = qMax(maxGroups, trackPatterns[track].size());
        }
    }
    
    // Play patterns in parallel (all tracks simultaneously)
    for (int groupIdx = 0; groupIdx < maxGroups; groupIdx++) {
        bool anyTrackHasPattern = false;
        
        // Start patterns for all tracks that have this group
        for (int track = 0; track < MAX_TRACKS; track++) {
            if (trackPatterns.contains(track) && groupIdx < trackPatterns[track].size()) {
                QString instrumentName = getInstrumentMacroName(m_tracks[track].instrument);
                int patternIndex = trackPatternIndices[track][groupIdx];
                
                stream << QString("  playPat %1, %2, 0, %3\n")
                          .arg(track)  // Channel
                          .arg(patternIndex)  // Pattern index
                          .arg(instrumentName);  // Instrument
                anyTrackHasPattern = true;
            }
        }
        
        if (anyTrackHasPattern) {
            // Wait for the pattern to complete
            stream << QString("  waitRows 16\n\n");
        }
    }
    
    stream << "\n  ; Composition end\n";
    stream << "  waitRows 32\n";
    stream << "  fine\n";
    
    file.close();
    qDebug() << "Music file saved in Pently format:" << filename;
    return true;
}

void SimpleWavWriter::addNote(int track, double time, int note, int velocity, double duration, int instrument)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    // Adjust note for Pently format (limit range)
    int adjustedNote = note;
    if (adjustedNote < 24) adjustedNote = 24; // C2
    if (adjustedNote > 84) adjustedNote = 84; // C6
    
    WavEvent event;
    event.track = track;
    event.time = time;
    event.note = adjustedNote;
    event.velocity = velocity;
    event.duration = duration * m_sampleRate;
    event.instrument = instrument;
    event.isPause = false;
    
    m_tracks[track].events.append(event);
    
    // Sort events by time
    std::sort(m_tracks[track].events.begin(), m_tracks[track].events.end(),
        [](const WavEvent& a, const WavEvent& b) {
            return a.time < b.time;
        });
    
    // Clear cached audio data
    m_tracks[track].audioData.clear();
    
    emit trackUpdated(track);
}

void SimpleWavWriter::addSilence(int track, double duration)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    // Find time of last event
    double lastTime = 0;
    if (!m_tracks[track].events.isEmpty()) {
        const WavEvent& lastEvent = m_tracks[track].events.last();
        lastTime = lastEvent.time + (double)lastEvent.duration / m_sampleRate;
    }
    
    WavEvent event;
    event.track = track;
    event.time = lastTime;
    event.note = 0;
    event.velocity = 0;
    event.duration = duration * m_sampleRate;
    event.instrument = 0;
    event.isPause = true;
    
    m_tracks[track].events.append(event);
    m_tracks[track].audioData.clear();
    
    emit trackUpdated(track);
}

void SimpleWavWriter::addPause(int track, double duration)
{
    addSilence(track, duration);
}

void SimpleWavWriter::clearTrack(int track)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    m_tracks[track].events.clear();
    m_tracks[track].audioData.clear();
    
    emit trackUpdated(track);
}

void SimpleWavWriter::clearAllTracks()
{
    for (int i = 0; i < MAX_TRACKS; i++) {
        m_tracks[i].events.clear();
        m_tracks[i].audioData.clear();
        emit trackUpdated(i);
    }
}

void SimpleWavWriter::mergeTrack(int fromTrack, int toTrack)
{
    if (fromTrack < 0 || fromTrack >= MAX_TRACKS || 
        toTrack < 0 || toTrack >= MAX_TRACKS || 
        fromTrack == toTrack) {
        return;
    }
    
    for (const auto& event : m_tracks[fromTrack].events) {
        m_tracks[toTrack].events.append(event);
    }
    
    // Sort events by time
    std::sort(m_tracks[toTrack].events.begin(), m_tracks[toTrack].events.end(),
        [](const WavEvent& a, const WavEvent& b) {
            return a.time < b.time;
        });
    
    m_tracks[toTrack].audioData.clear();
    m_tracks[fromTrack].events.clear();
    m_tracks[fromTrack].audioData.clear();
    
    emit trackUpdated(fromTrack);
    emit trackUpdated(toTrack);
}

void SimpleWavWriter::copyTrack(int fromTrack, int toTrack)
{
    if (fromTrack < 0 || fromTrack >= MAX_TRACKS || 
        toTrack < 0 || toTrack >= MAX_TRACKS || 
        fromTrack == toTrack) {
        return;
    }
    
    m_tracks[toTrack].events = m_tracks[fromTrack].events;
    m_tracks[toTrack].audioData.clear();
    
    emit trackUpdated(toTrack);
}

void SimpleWavWriter::setTrackName(int track, const QString &name)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    m_tracks[track].name = name;
    emit trackUpdated(track);
}

void SimpleWavWriter::setTrackInstrument(int track, int instrument)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    m_tracks[track].instrument = instrument;
    emit trackUpdated(track);
}

void SimpleWavWriter::muteTrack(int track, bool muted)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    m_tracks[track].muted = muted;
    emit trackUpdated(track);
}

void SimpleWavWriter::setTrackVolume(int track, double volume)
{
    if (track < 0 || track >= MAX_TRACKS) return;
    
    m_tracks[track].volume = qBound(0.0, volume, 2.0);
    emit trackUpdated(track);
}

QByteArray SimpleWavWriter::getTrackAudioData(int track, bool preview)
{
    if (track < 0 || track >= MAX_TRACKS || m_tracks[track].muted) {
        return QByteArray();
    }
    
    if (m_tracks[track].audioData.isEmpty()) {
        m_tracks[track].audioData = generateTrackAudio(track, !preview);
    }
    
    return m_tracks[track].audioData;
}

QByteArray SimpleWavWriter::getAllTracksAudioData()
{
    QByteArray allData;
    
    // First, find the longest track
    int maxSamples = 0;
    QVector<QByteArray> trackDataList;
    
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (!m_tracks[track].events.isEmpty() && !m_tracks[track].muted) {
            QByteArray trackData = getTrackAudioData(track);
            if (!trackData.isEmpty()) {
                trackDataList.append(trackData);
                maxSamples = qMax(maxSamples, trackData.size() / 2);
            }
        }
    }
    
    if (trackDataList.isEmpty()) {
        return QByteArray();
    }
    
    // Create buffer for mixed audio
    allData.resize(maxSamples * 2); // 16-bit = 2 bytes per sample
    memset(allData.data(), 0, allData.size());
    
    // Mix all tracks
    for (const QByteArray& trackData : trackDataList) {
        int trackSamples = trackData.size() / 2;
        const int16_t* trackPtr = reinterpret_cast<const int16_t*>(trackData.constData());
        int16_t* allPtr = reinterpret_cast<int16_t*>(allData.data());
        
        for (int i = 0; i < qMin(trackSamples, maxSamples); i++) {
            // Mix with clipping prevention
            int32_t mixed = allPtr[i] + trackPtr[i];
            if (mixed > 32767) mixed = 32767;
            if (mixed < -32768) mixed = -32768;
            allPtr[i] = static_cast<int16_t>(mixed);
        }
    }
    
    return allData;
}

QByteArray SimpleWavWriter::getMergedAudioData()
{
    return getAllTracksAudioData();
}

bool SimpleWavWriter::loadWavToTrack(const QString &filename, int track)
{
    if (track < 0 || track >= MAX_TRACKS) {
        return false;
    }
    
    QVector<int16_t> samples;
    int fileSampleRate;
    
    if (!loadWavFile(filename, samples, fileSampleRate)) {
        return false;
    }
    
    // Clear current track
    clearTrack(track);
    
    // Convert samples to events (simplified - one note with samples)
    if (!samples.isEmpty()) {
        // Create one event for entire WAV file
        WavEvent event;
        event.track = track;
        event.time = 0;
        event.note = 60; // C4 default
        event.velocity = 100;
        event.duration = samples.size(); // Duration in samples
        event.instrument = 0; // Default
        event.isPause = false;
        
        m_tracks[track].events.append(event);
        
        // Set track volume
        m_tracks[track].volume = 0.7;
        
        emit trackUpdated(track);
        qDebug() << "Loaded WAV file to track" << track << "samples:" << samples.size();
        return true;
    }
    
    return false;
}

int SimpleWavWriter::getEventCount(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return 0;
    return m_tracks[track].events.size();
}

QString SimpleWavWriter::getTrackName(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return QString();
    return m_tracks[track].name;
}

int SimpleWavWriter::getTrackInstrument(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return 0;
    return m_tracks[track].instrument;
}

double SimpleWavWriter::getTrackVolume(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return 0;
    return m_tracks[track].volume;
}

bool SimpleWavWriter::isTrackMuted(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return true;
    return m_tracks[track].muted;
}

QVector<WavEvent> SimpleWavWriter::getTrackEvents(int track) const
{
    if (track < 0 || track >= MAX_TRACKS) return QVector<WavEvent>();
    return m_tracks[track].events;
}

double SimpleWavWriter::getTotalDuration() const
{
    double maxDuration = 0;
    
    for (int track = 0; track < MAX_TRACKS; track++) {
        double trackDuration = getTrackDuration(track);
        if (trackDuration > maxDuration) {
            maxDuration = trackDuration;
        }
    }
    
    return maxDuration;
}

double SimpleWavWriter::getTrackDuration(int track) const
{
    if (track < 0 || track >= MAX_TRACKS || m_tracks[track].events.isEmpty()) {
        return 0;
    }
    
    const WavEvent& lastEvent = m_tracks[track].events.last();
    return lastEvent.time + (double)lastEvent.duration / m_sampleRate;
}

QByteArray SimpleWavWriter::synthesizeTrackPreview(int track)
{
    return generateTrackAudio(track, false);
}

void SimpleWavWriter::writeWavHeader(QDataStream &stream, quint32 dataSize)
{
    // RIFF header
    stream.writeRawData("RIFF", 4);
    quint32 chunkSize = 36 + dataSize;
    stream << chunkSize;
    stream.writeRawData("WAVE", 4);
    
    // fmt chunk
    stream.writeRawData("fmt ", 4);
    quint32 subchunk1Size = 16;
    stream << subchunk1Size;
    
    quint16 audioFormat = 1; // PCM
    stream << audioFormat;
    
    quint16 numChannels = 1; // Mono
    stream << numChannels;
    
    quint32 sampleRate = m_sampleRate;
    stream << sampleRate;
    
    quint32 byteRate = sampleRate * numChannels * 2; // 16-bit = 2 bytes
    stream << byteRate;
    
    quint16 blockAlign = numChannels * 2;
    stream << blockAlign;
    
    quint16 bitsPerSample = 16;
    stream << bitsPerSample;
    
    // data chunk
    stream.writeRawData("data", 4);
    stream << dataSize;
}

QByteArray SimpleWavWriter::generateTrackAudio(int track, bool includeEffects)
{
    if (track < 0 || track >= MAX_TRACKS || m_tracks[track].events.isEmpty()) {
        return QByteArray();
    }
    
    QByteArray audioData;
    QDataStream stream(&audioData, QIODevice::WriteOnly);
    stream.setByteOrder(QDataStream::LittleEndian);
    
    double trackDuration = getTrackDuration(track);
    int totalSamples = static_cast<int>(trackDuration * m_sampleRate);
    
    // Create buffer for samples
    QVector<double> sampleBuffer(totalSamples, 0.0);
    
    // Generate each event
    for (const auto& event : m_tracks[track].events) {
        if (event.isPause) continue;
        
        double frequency = noteToFrequency(event.note);
        int startSample = static_cast<int>(event.time * m_sampleRate);
        int endSample = startSample + event.duration;
        
        // Determine gain for bass notes
        double volumeMultiplier = 1.0;
        if (event.instrument >= 28 && event.instrument <= 40) {
            volumeMultiplier = m_bassVolumeMultiplier;
        }
        
        // Consider track volume
        volumeMultiplier *= m_tracks[track].volume * m_masterVolume;
        
        double baseAmplitude = (event.velocity / 127.0) * 0.7 * volumeMultiplier;
        
        // Envelope parameters for this instrument
        double attack = getAttackForInstrument(event.instrument);
        double decay = getDecayForInstrument(event.instrument);
        double sustain = getSustainForInstrument(event.instrument);
        double release = getReleaseForInstrument(event.instrument);
        
        // Generate note
        for (int i = 0; i < event.duration && (startSample + i) < totalSamples; i++) {
            double noteTime = static_cast<double>(i) / m_sampleRate;
            double noteDuration = static_cast<double>(event.duration) / m_sampleRate;
            
            // ADSR envelope
            double envelope = 1.0;
            if (includeEffects) {
                envelope = adsrEnvelope(noteTime, noteDuration, attack, decay, sustain, release);
            }
            
            // Amplitude with envelope
            double amplitude = baseAmplitude * envelope;
            
            // Limit amplitude to avoid clipping
            if (amplitude > 1.0) amplitude = 1.0;
            
            // Generate wave
            double t = event.time + noteTime;
            double sampleValue = 0.0;
            
            if (includeEffects) {
                short sample = generateWaveform(t, frequency, amplitude, event.instrument);
                sampleValue = static_cast<double>(sample) / 32767.0;
            } else {
                // For preview use simple sine
                sampleValue = sin(2.0 * M_PI * frequency * t) * amplitude;
            }
            
            // Add to buffer
            sampleBuffer[startSample + i] += sampleValue;
        }
    }
    
    // Convert buffer to 16-bit samples
    for (double sampleValue : sampleBuffer) {
        // Limit value to avoid clipping
        if (sampleValue > 1.0) sampleValue = 1.0;
        if (sampleValue < -1.0) sampleValue = -1.0;
        
        short sample = static_cast<short>(sampleValue * 32767.0);
        stream << sample;
    }
    
    return audioData;
}

void SimpleWavWriter::generateAllTracksAudio()
{
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (!m_tracks[track].events.isEmpty()) {
            m_tracks[track].audioData = generateTrackAudio(track, true);
            emit audioDataReady(track, m_tracks[track].audioData);
        }
    }
}

double SimpleWavWriter::adsrEnvelope(double noteTime, double noteDuration, 
                                   double attack, double decay, 
                                   double sustain, double release)
{
    double envelope = 1.0;
    
    if (noteTime < attack) {
        // Attack
        envelope = noteTime / attack;
    } else if (noteTime < attack + decay) {
        // Decay
        envelope = 1.0 - ((noteTime - attack) / decay) * (1.0 - sustain);
    } else if (noteTime < noteDuration - release) {
        // Sustain
        envelope = sustain;
    } else if (noteTime < noteDuration) {
        // Release
        double releaseTime = noteTime - (noteDuration - release);
        envelope = sustain * (1.0 - releaseTime / release);
    } else {
        // After release
        envelope = 0.0;
    }
    
    return envelope;
}

double SimpleWavWriter::sineWave(double phase)
{
    return sin(2.0 * M_PI * phase);
}

double SimpleWavWriter::squareWave(double phase)
{
    return sin(2.0 * M_PI * phase) > 0 ? 0.7 : -0.7;
}

double SimpleWavWriter::sawtoothWave(double phase)
{
    return 2.0 * (phase - floor(phase + 0.5));
}

double SimpleWavWriter::triangleWave(double phase)
{
    double x = 2.0 * (phase - floor(phase + 0.5));
    return 2.0 * fabs(x) - 1.0;
}

double SimpleWavWriter::noiseWave()
{
    return (2.0 * rand() / RAND_MAX) - 1.0;
}

double SimpleWavWriter::lowPassFilter(double input, double &prev, double cutoff)
{
    double RC = 1.0 / (2.0 * M_PI * cutoff);
    double dt = 1.0 / m_sampleRate;
    double alpha = dt / (RC + dt);
    double output = prev + alpha * (input - prev);
    prev = output;
    return output;
}

double SimpleWavWriter::highPassFilter(double input, double &prevInput, double &prevOutput, double cutoff)
{
    double RC = 1.0 / (2.0 * M_PI * cutoff);
    double dt = 1.0 / m_sampleRate;
    double alpha = RC / (RC + dt);
    double output = alpha * (prevOutput + input - prevInput);
    prevInput = input;
    prevOutput = output;
    return output;
}

double SimpleWavWriter::noteToFrequency(int note)
{
    return 440.0 * pow(2.0, (note - 69) / 12.0);
}

int SimpleWavWriter::frequencyToNote(double frequency)
{
    return static_cast<int>(69 + 12 * log2(frequency / 440.0));
}

QString SimpleWavWriter::noteNumberToName(int note)
{
    static const QString noteNames[] = {
        "C", "CS", "D", "DS", "E", "F", "FS", "G", "GS", "A", "AS", "B"
    };
    
    int octave = note / 12;
    int noteIndex = note % 12;
    
    QString name = noteNames[noteIndex];
    
    // Add octave designation for Pently format
    if (octave >= 5) {
        name += "HH"; // High high
    } else if (octave == 4) {
        name += "H";  // High
    } else if (octave == 3) {
        // First octave - no suffix
    } else if (octave == 2) {
        name += "L";  // Low
    } else if (octave <= 1) {
        name += "LL"; // Low low
    }
    
    return name;
}

QString SimpleWavWriter::getDurationSymbol(int durationSamples)
{
    double durationSeconds = static_cast<double>(durationSamples) / m_sampleRate;
    
    // Convert to note durations for Pently
    if (durationSeconds >= 2.0) return "1";
    else if (durationSeconds >= 1.5) return "D2";
    else if (durationSeconds >= 1.0) return "2";
    else if (durationSeconds >= 0.75) return "D4";
    else if (durationSeconds >= 0.5) return "4";
    else if (durationSeconds >= 0.375) return "D8";
    else if (durationSeconds >= 0.25) return "8";
    else if (durationSeconds >= 0.1875) return "D16";
    else if (durationSeconds >= 0.125) return "16";
    else if (durationSeconds >= 0.09375) return "D32";
    else return "32";
}

QString SimpleWavWriter::getInstrumentMacroName(int instrument)
{
    // Mapping instruments to Pently macros
    static QMap<int, QString> instrumentMap = {
        {1, "PLING_2"},      // CrandPno -> PLING_2
        {2, "PLING_4"},      // BritePno -> PLING_4
        {3, "XYLSHORT"},     // Harpsi -> XYLSHORT
        {6, "XYLSHORT"},     // Harpsi -> XYLSHORT
        {25, "PLING_8"},     // ClassicGt -> PLING_8
        {27, "PLING_8"},     // JazzGtr -> PLING_8
        {28, "BASSGUITAR"},  // FngrBass -> BASSGUITAR
        {29, "PLING_4"},     // Ovrdrive -> PLING_4
        {33, "BASSGUITAR"},  // FngrBass -> BASSGUITAR
        {37, "PLING_4"},     // Ovrdrive -> PLING_4
        {38, "PLING_4"},     // DstGtr -> PLING_4
        {39, "BASSGUITAR"},  // FngrBass -> BASSGUITAR
        {40, "BASSGUITAR"},  // SlapBas -> BASSGUITAR
        {48, "HORNBLAT"},    // String -> HORNBLAT
        {49, "HORNBLAT"},    // SlowStr -> HORNBLAT
        {81, "BASSCLAR"},    // LeadSx -> BASSCLAR
        {89, "PLING_8"},     // SoftPad -> PLING_8
        {95, "XYLSHORT"},    // Bright -> XYLSHORT
        {96, "XYLSHORT"},    // Bright -> XYLSHORT
        {100, "XYLSHORT"}    // Bright -> XYLSHORT
    };
    
    return instrumentMap.value(instrument, "PLING_2");
}

WaveformType SimpleWavWriter::getWaveformForInstrument(int instrument)
{
    // Determine waveform by instrument type
    if (instrument == 1) return WAVEFORM_SINE;          // CrandPno - sine
    if (instrument == 2) return WAVEFORM_SQUARE;        // BritePno - square
    if (instrument == 3 || instrument == 6) return WAVEFORM_SQUARE; // Harpsi - square
    if (instrument == 25 || instrument == 27) return WAVEFORM_TRIANGLE; // Guitars - triangle
    if (instrument >= 28 && instrument <= 40) return WAVEFORM_SAWTOOTH; // Bass - sawtooth
    if (instrument == 48 || instrument == 49) return WAVEFORM_SINE;     // Strings - sine
    if (instrument == 81) return WAVEFORM_TRIANGLE;     // Saxophone - triangle
    if (instrument == 89) return WAVEFORM_SINE;         // SoftPad - sine
    if (instrument >= 95 && instrument <= 100) return WAVEFORM_SQUARE; // Bright - square
    
    return WAVEFORM_SINE; // Default
}

double SimpleWavWriter::getFilterCutoffForInstrument(int instrument)
{
    // Filter cutoff frequency
    if (instrument >= 28 && instrument <= 40) return 400.0; // Bass - low frequencies
    if (instrument == 1) return 1000.0; // Piano
    if (instrument == 2) return 2000.0; // Bright piano
    if (instrument == 3 || instrument == 6) return 1500.0; // Harpsichord
    if (instrument == 25 || instrument == 27) return 800.0; // Guitars
    if (instrument == 81) return 600.0;  // Saxophone
    return 1000.0; // Default
}

double SimpleWavWriter::getAttackForInstrument(int instrument)
{
    // Attack time
    if (instrument >= 28 && instrument <= 40) return 0.1;  // Bass - slow attack
    if (instrument == 1) return 0.05;  // Piano
    if (instrument == 2) return 0.02;  // Bright piano - fast attack
    if (instrument == 3 || instrument == 6) return 0.01; // Harpsichord - very fast
    if (instrument == 81) return 0.08;  // Saxophone
    return 0.05;
}

double SimpleWavWriter::getDecayForInstrument(int instrument)
{
    // Decay time
    if (instrument >= 28 && instrument <= 40) return 0.2;  // Bass
    if (instrument == 1) return 0.1;   // Piano
    if (instrument == 2) return 0.05;  // Bright piano
    if (instrument == 3 || instrument == 6) return 0.02; // Harpsichord
    return 0.1;
}

double SimpleWavWriter::getSustainForInstrument(int instrument)
{
    // Sustain level
    if (instrument >= 28 && instrument <= 40) return 0.8;  // Bass - high sustain
    if (instrument == 1) return 0.7;   // Piano
    if (instrument == 2) return 0.6;   // Bright piano
    if (instrument == 3 || instrument == 6) return 0.5; // Harpsichord - fast decay
    if (instrument == 81) return 0.9;  // Saxophone - long sustain
    return 0.7;
}

double SimpleWavWriter::getReleaseForInstrument(int instrument)
{
    // Release time
    if (instrument >= 28 && instrument <= 40) return 0.3;  // Bass - long release
    if (instrument == 1) return 0.2;   // Piano
    if (instrument == 2) return 0.1;   // Bright piano
    if (instrument == 3 || instrument == 6) return 0.05; // Harpsichord - short
    if (instrument == 81) return 0.4;  // Saxophone - long
    return 0.2;
}

QString SimpleWavWriter::generatePentlyPattern(int track, int patternIndex)
{
    // Group events by time to create pattern
    QVector<QVector<WavEvent>> groups = groupEventsByTime(track, 1.0);
    
    if (patternIndex >= groups.size()) {
        return QString();
    }
    
    QString patternData;
    const QVector<WavEvent>& events = groups[patternIndex];
    
    // Add notes to pattern
    for (const auto& event : events) {
        if (!event.isPause) {
            QString noteName = noteNumberToName(event.note);
            QString duration = getDurationSymbol(event.duration);
            patternData += QString("  .byt N_%1|D_%2\n").arg(noteName).arg(duration);
        } else {
            // Pause
            QString duration = getDurationSymbol(event.duration);
            patternData += QString("  .byt REST|D_%1\n").arg(duration);
        }
    }
    
    return patternData;
}

QString SimpleWavWriter::generatePentlySong()
{
    QString songData;
    
    songData += "PSDAT_composition:\n";
    songData += "  setTempo 300\n\n";
    
    // For each track add patterns
    int patternCounter = 0;
    for (int track = 0; track < MAX_TRACKS; track++) {
        if (m_tracks[track].events.isEmpty()) continue;
        
        QVector<QVector<WavEvent>> groups = groupEventsByTime(track, 1.0);
        QString instrumentName = getInstrumentMacroName(m_tracks[track].instrument);
        
        for (int i = 0; i < groups.size(); i++) {
            songData += QString("  playPat %1, %2, 0, %3\n")
                           .arg(track)
                           .arg(patternCounter)
                           .arg(instrumentName);
            patternCounter++;
        }
        
        if (track < MAX_TRACKS - 1 && !m_tracks[track + 1].events.isEmpty()) {
            songData += "  waitRows 16\n";
        }
    }
    
    songData += "\n  waitRows 32\n";
    songData += "  fine\n";
    
    return songData;
}

QVector<QVector<WavEvent>> SimpleWavWriter::groupEventsByTime(int track, double timeThreshold)
{
    QVector<QVector<WavEvent>> groups;
    
    if (track < 0 || track >= MAX_TRACKS || m_tracks[track].events.isEmpty()) {
        return groups;
    }
    
    QVector<WavEvent> currentGroup;
    double lastTime = -timeThreshold * 2; // So first event always starts new group
    
    for (const auto& event : m_tracks[track].events) {
        if (event.time - lastTime > timeThreshold && !currentGroup.isEmpty()) {
            groups.append(currentGroup);
            currentGroup.clear();
        }
        
        currentGroup.append(event);
        lastTime = event.time;
    }
    
    if (!currentGroup.isEmpty()) {
        groups.append(currentGroup);
    }
    
    return groups;
}

QString SimpleWavWriter::getNoteCommand(const WavEvent &event, bool includeInstrument)
{
    if (event.isPause) {
        QString duration = getDurationSymbol(event.duration);
        return QString("REST|D_%1").arg(duration);
    }
    
    QString noteName = noteNumberToName(event.note);
    QString duration = getDurationSymbol(event.duration);
    
    if (includeInstrument) {
        QString instrumentName = getInstrumentMacroName(event.instrument);
        return QString("INSTRUMENT, %1, N_%2|D_%3").arg(instrumentName).arg(noteName).arg(duration);
    } else {
        return QString("N_%1|D_%2").arg(noteName).arg(duration);
    }
}

bool SimpleWavWriter::decodeWavData(const QByteArray &wavData, QVector<int16_t> &samples, int &sampleRate)
{
    // Simplified WAV decoding (only 16-bit mono)
    if (wavData.size() < 44) return false; // Minimum WAV header size
    
    // Check RIFF header
    if (wavData.mid(0, 4) != "RIFF") return false;
    if (wavData.mid(8, 4) != "WAVE") return false;
    
    // Find fmt chunk
    int offset = 12;
    while (offset < wavData.size() - 8) {
        QString chunkId = QString::fromLatin1(wavData.mid(offset, 4));
        int chunkSize = *(int*)(wavData.constData() + offset + 4);
        
        if (chunkId == "fmt ") {
            // Read parameters
            int audioFormat = *(short*)(wavData.constData() + offset + 8);
            if (audioFormat != 1) return false; // Only PCM
            
            int channels = *(short*)(wavData.constData() + offset + 10);
            sampleRate = *(int*)(wavData.constData() + offset + 12);
            int bitsPerSample = *(short*)(wavData.constData() + offset + 22);
            
            if (channels != 1 || bitsPerSample != 16) {
                qDebug() << "Only 16-bit mono WAV files are supported";
                return false;
            }
        } else if (chunkId == "data") {
            // Read audio data
            int dataSize = chunkSize;
            int dataOffset = offset + 8;
            
            if (dataOffset + dataSize > wavData.size()) {
                return false;
            }
            
            samples.resize(dataSize / 2); // 16-bit = 2 bytes per sample
            
            const char* data = wavData.constData() + dataOffset;
            for (int i = 0; i < samples.size(); i++) {
                samples[i] = *(int16_t*)(data + i * 2);
            }
            
            return true;
        }
        
        offset += 8 + chunkSize;
    }
    
    return false;
}

bool SimpleWavWriter::loadWavFile(const QString &filename, QVector<int16_t> &samples, int &sampleRate)
{
    QFile file(filename);
    if (!file.open(QIODevice::ReadOnly)) {
        qDebug() << "Cannot open WAV file:" << filename;
        return false;
    }
    
    QByteArray wavData = file.readAll();
    file.close();
    
    return decodeWavData(wavData, samples, sampleRate);
}

short SimpleWavWriter::generateWaveform(double time, double frequency, double amplitude, int instrument)
{
    double phase = fmod(time * frequency, 1.0);
    double value = 0.0;
    
    WaveformType waveform = getWaveformForInstrument(instrument);
    
    switch (waveform) {
    case WAVEFORM_SINE:
        value = sineWave(phase);
        break;
    case WAVEFORM_SQUARE:
        value = squareWave(phase);
        // Add some harmonics for square wave
        for (int i = 3; i <= 9; i += 2) {
            value += 0.7 / i * sin(2.0 * M_PI * frequency * i * time);
        }
        break;
    case WAVEFORM_SAWTOOTH:
        value = sawtoothWave(phase);
        // Add harmonics for sawtooth wave
        for (int i = 2; i <= 10; i++) {
            value += 0.5 / i * sin(2.0 * M_PI * frequency * i * time);
        }
        break;
    case WAVEFORM_TRIANGLE:
        value = triangleWave(phase);
        // Add odd harmonics for triangle wave
        for (int i = 3; i <= 9; i += 2) {
            value += 0.8 / (i * i) * sin(2.0 * M_PI * frequency * i * time);
        }
        break;
    case WAVEFORM_NOISE:
        value = noiseWave();
        break;
    }
    
    // Apply filter based on instrument
    static double prevLP = 0;
    static double prevHPInput = 0;
    static double prevHPOutput = 0;
    
    double cutoff = getFilterCutoffForInstrument(instrument);
    
    if (instrument >= 28 && instrument <= 40) {
        // Bass - strong low-pass filter
        value = lowPassFilter(value, prevLP, cutoff);
    } else if (instrument == 3 || instrument == 6) {
        // Harpsichord - some high-pass for brightness
        value = highPassFilter(value, prevHPInput, prevHPOutput, 500.0);
    }
    
    // Limit value to avoid clipping
    if (value > 1.0) value = 1.0;
    if (value < -1.0) value = -1.0;
    
    return static_cast<short>(value * amplitude * 32767.0);
}

void SimpleWavWriter::clear()
{
    clearAllTracks();
    m_isRecording = false;
    m_isPaused = false;
}