; Generated by Yamitracker
; Date: 2025-12-13 14:06:47

music_inst_table:
  INST CrandPno,         11, 10,  3,  6, 31, 17,  0,  8
  INST CrandPno,         11, 10,  3,  6, 31, 17,  0,  8

pently_patterns:
  .addr PPDAT_track0
  .addr PPDAT_track1

PPDAT_track0:
  .byt D_1
  .byt N_CH|D_D8
  .byt N_CH|D_D16
  .byt D_D4
  .byt N_CH|D_D16
  .byt N_CH|D_D8
  .byt D_D8
  .byt N_DH|D_D16
  .byt N_DH|D_D8
  .byt D_D4
  .byt N_EH|D_D16
  .byt N_EH|D_D8
  .byt D_D4
  .byt N_FH|D_D16
  .byt N_FH|D_D8
  .byt D_D4
  .byt N_CH|D_D16
  .byt N_CH|D_D8
  .byt D_D8
  .byt N_CH|D_D16
  .byt N_CH|D_D8
  .byt D_D8
  .byt N_DH|D_D16
  .byt N_DH|D_D8
  .byt D_D8
  .byt N_EH|D_D16
  .byt N_EH|D_D8
  .byt D_D4
  .byt N_FH|D_D16
  .byt N_FH|D_D8
  .byt D_D8
  .byt N_CH|D_D16
  .byt N_CH|D_D8
  .byt D_D8
  .byt N_CH|D_D16
  .byt N_CH|D_D8
  .byt D_D8
  .byt N_DH|D_D16
  .byt N_DH|D_D16
  .byt D_D4
  .byt N_EH|D_D16
  .byt N_EH|D_D16
  .byt D_D4
  .byt N_FH|D_D16
  .byt N_FH|D_D8
  .byt D_D4
  .byt N_CH|D_D16
  .byt N_CH|D_D16
  .byt PATEND

PPDAT_track1:
  .byt D_2
  .byt N_F|D_D8
  .byt N_F|D_D16
  .byt D_D16
  .byt N_G|D_D8
  .byt N_G|D_D16
  .byt D_D8
  .byt N_A|D_D16
  .byt N_A|D_D8
  .byt D_D8
  .byt N_B|D_D16
  .byt N_B|D_D16
  .byt D_D8
  .byt N_C|D_D16
  .byt N_C|D_D8
  .byt D_D8
  .byt N_F|D_D16
  .byt N_F|D_D8
  .byt D_D16
  .byt N_G|D_D16
  .byt N_G|D_D16
  .byt D_D8
  .byt N_A|D_D16
  .byt N_A|D_D8
  .byt D_D8
  .byt N_B|D_D16
  .byt N_B|D_D16
  .byt D_D8
  .byt N_C|D_D16
  .byt N_C|D_D16
  .byt D_D8
  .byt N_F|D_D16
  .byt N_F|D_D8
  .byt D_D16
  .byt N_G|D_D16
  .byt N_G|D_D16
  .byt D_D8
  .byt N_A|D_D16
  .byt N_A|D_D16
  .byt D_D8
  .byt N_B|D_D16
  .byt N_B|D_D8
  .byt D_D8
  .byt N_C|D_D16
  .byt N_C|D_D8
  .byt D_D8
  .byt N_F|D_D16
  .byt N_F|D_D8
  .byt D_D8
  .byt N_G|D_D16
  .byt N_G|D_D8
  .byt D_D8
  .byt N_A|D_D16
  .byt N_A|D_D16
  .byt D_D8
  .byt N_B|D_D16
  .byt N_B|D_D8
  .byt D_D8
  .byt N_C|D_D8
  .byt N_C|D_D16
  .byt D_D8
  .byt N_F|D_D16
  .byt N_F|D_D8
  .byt D_D4
  .byt N_G|D_D16
  .byt N_G|D_D8
  .byt D_D8
  .byt N_A|D_D16
  .byt N_A|D_D8
  .byt D_D8
  .byt N_B|D_D16
  .byt N_B|D_D8
  .byt D_D8
  .byt N_C|D_D16
  .byt N_C|D_D4
  .byt D_D4
  .byt N_F|D_D16
  .byt N_F|D_D8
  .byt PATEND

pently_songs:
.addr  PSDAT_track0, PSDAT_track1, 

PSDAT_track0:
  setTempo 1000
  playPat 0, 0, 23, CrandPno
  waitRows 255
  dalSegno

PSDAT_track1:
  setTempo 1000
  playPat 1, 1, 23, CrandPno
  waitRows 255
  dalSegno
